
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[380] =
    {   0,
        0,    0,    0,    0,  114,  113,    1,  111,  113,   13,
        7,    6,   12,  113,  113,   14,   10,   11,    4,    3,
        5,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,    9,    8,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,   20,   21,   17,   18,
       19,    1,    0,   16,   14,    2,   15,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  105,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,

      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,   60,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,   15,
      112,  112,  112,  112,   99,  112,  112,  112,  100,  101,
      112,   29,  112,  112,  112,  112,  112,  112,  102,  112,
      112,  104,  109,  112,  112,  112,  112,   41,  108,  112,
      112,  112,  112,  110,   45,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,   71,

      112,  112,  112,   75,   79,  112,  112,   84,  112,   87,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,   24,  112,  112,  112,   27,  112,   30,  112,
      112,   33,   34,  112,   36,  112,  103,  106,  112,   39,
      112,   42,  112,   43,  112,  112,   47,  112,  112,  112,
       51,  112,  112,  112,   56,   53,  112,   58,  112,  112,
       62,  112,  112,  112,  112,  112,  112,  112,   70,  112,
      112,  112,   76,   77,  112,   80,   81,  112,  112,  112,
       86,  112,   89,  112,  112,   92,  112,  112,  112,  112,
       97,  112,   23,  112,   25,  112,  112,  112,   32,   35,

      112,  112,  112,  107,   44,   46,   48,  112,   50,   52,
       54,   55,  112,  112,  112,  112,   63,   65,   66,   67,
       68,   69,  112,  112,   74,  112,  112,  112,  112,  112,
       90,  112,  112,   94,  112,  112,   22,   98,   26,  112,
      112,   37,  112,   40,  112,   57,   59,  112,   64,  112,
       72,   78,   82,  112,   85,  112,   91,  112,  112,   96,
      112,  112,   38,   49,  112,  112,   83,   88,  112,   95,
      112,   31,   61,   73,   93,  112,  112,   28,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       16,   15,   15,   15,   15,   15,   15,   17,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   31,   32,   33,   34,   35,   36,
       31,   37,   38,   39,   40,   31,   41,   42,   43,   44,
       45,    1,   46,    1,   31,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   31,   31,   56,   57,   58,
       59,   60,   31,   61,   62,   63,   64,   65,   31,   66,
       67,   68,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    2,    1,    2,    2,    1,    1,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[382] =
    {   0,
        0,    0,   59,   62,  413,  414,  410,  414,   72,  414,
      414,  414,  414,   62,  402,   66,  414,  414,  414,  414,
      414,   47,  370,   61,   62,  375,    0,  382,  381,  372,
      383,   59,   75,  378,   65,  373,  365,  358,  414,  414,
       29,  341,   56,   58,  341,  337,  336,   56,  349,   72,
       58,   85,   89,   90,   95,  336,  414,  107,    0,    0,
        0,  392,  148,  414,  143,  414,  145,    0,  370,  353,
      361,  358,  362,  366,  352,  360,  360,  345,  343,  137,
      348,  349,  350,  356,  344,  361,  130,  353,    0,  342,
      339,  343,   71,  333,  344,  335,  346,  335,  337,  322,

      309,  311,  305,  301,  314,  106,  119,   81,  313,  308,
      311,  307,    0,   86,  106,  297,  296,  299,  302,  118,
      301,  288,  295,  288,  293,  292,  288,   21,  278,  282,
      280,  277,  286,  284,  292,  281,  274,  275,  279,  155,
      308,  311,  300,  307,    0,  293,  292,  306,    0,  301,
      303,    0,  288,  298,   81,  284,  296,  291,    0,  290,
      284,    0,    0,  279,  284,  291,  280,    0,    0,  278,
      270,  286,  272,    0,    0,  254,  259,  245,  246,  245,
      238,  240,  248,  251,  238,  252,  236,  249,  234,  233,
      244,  232,  121,  235,  236,  229,  230,  226,  227,    0,

      232,  235,  238,  127,  135,  222,  224,    0,  221,    0,
      233,  229,  227,  227,  214,  219,  219,  212,  209,  235,
      247,  245,    0,  236,  243,  228,    0,  234,    0,  228,
      222,    0,    0,  231,    0,  235,    0,    0,  239,    0,
      223,    0,  227,    0,  232,  206,    0,  205,  202,  204,
        0,  200,  187,  201,    0,    0,  191,    0,  190,  187,
        0,  183,  183,  195,  194,  192,  180,  179,    0,  183,
      181,  181,    0,    0,  179,    0,    0,  178,  184,  174,
        0,  174,    0,  169,  173,    0,  179,  178,  173,  170,
        0,  197,    0,  192,    0,  198,  197,  200,    0,    0,

      178,  183,  194,    0,    0,    0,    0,  167,    0,    0,
        0,    0,  161,  160,  157,  156,    0,    0,    0,    0,
        0,    0,  158,  149,    0,  162,  161,  158,  145,  149,
        0,  143,  142,    0,  145,  152,    0,    0,    0,  173,
      162,    0,  157,    0,  137,    0,    0,  151,    0,  129,
        0,    0,    0,  146,    0,  145,    0,  133,  135,    0,
      163,  162,    0,    0,  131,  134,    0,    0,  117,    0,
      147,    0,    0,    0,    0,  147,  132,    0,  414,  190,
      136
    } ;

static yyconst flex_int16_t yy_def[382] =
    {   0,
      379,    1,    1,    1,  379,  379,  379,  379,  380,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  379,  379,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  379,  379,  381,  381,
      381,  379,  380,  379,  379,  379,  379,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  379,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,    0,  379,
      379
    } ;

static yyconst flex_int16_t yy_nxt[483] =
    {   0,
        6,    7,    8,    9,   10,    6,   11,   12,    6,    6,
       13,   14,    6,   15,   16,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       27,   31,   32,   27,   27,   33,   34,   35,   36,   27,
       37,   38,   27,   27,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   27,   48,   27,   49,   50,   51,   52,
       53,   54,   55,   27,   56,   27,   27,   27,   57,  207,
       58,   57,  208,   58,   64,   64,   65,   65,   67,   69,
       65,   65,   72,   78,  101,   70,  102,   73,   85,   74,
       94,   86,  166,   87,  167,   75,   79,   76,   77,   88,

       95,   89,  104,   96,   90,  113,   91,   97,  107,  105,
      231,   92,  108,  114,  106,  121,  232,  122,  123,  116,
      109,   65,   65,  117,   59,   60,   61,   59,   60,   61,
      118,  124,  119,  120,  184,  127,  132,   68,  125,  128,
      190,  129,  185,  133,  134,  130,  126,  131,  191,  137,
       64,   64,  135,  138,  160,   67,  136,   65,   65,  140,
      140,  152,  153,  161,  180,  181,  182,  192,  198,  140,
      140,  193,  262,  378,  273,  263,  377,  274,  376,  183,
      199,  275,  276,  375,  374,  277,  373,  372,  371,  278,
       63,   63,  370,  369,  368,  367,  366,  365,  364,  363,

      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  261,  260,  233,  259,  258,  257,  256,

      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  206,  205,  204,  203,  202,
      201,  200,  197,  196,  195,  194,  189,  188,  187,  186,
      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  165,  164,  163,  162,  159,  158,  157,  156,
      155,  154,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,   62,  139,  115,  112,  111,  110,  103,

      100,   99,   98,   93,   84,   83,   82,   81,   80,   71,
       66,   62,  379,    5,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379
    } ;

static yyconst flex_int16_t yy_chk[483] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,  128,
        3,    4,  128,    4,    9,    9,   14,   14,   16,   22,
       16,   16,   24,   25,   41,   22,   41,   24,   32,   24,
       35,   32,   93,   32,   93,   24,   25,   24,   24,   33,

       35,   33,   43,   35,   33,   48,   33,   35,   44,   43,
      155,   33,   44,   48,   43,   51,  155,   51,   51,   50,
       44,   58,   58,   50,    3,    3,    3,    4,    4,    4,
       50,   52,   50,   50,  108,   53,   54,  381,   52,   53,
      114,   53,  108,   54,   54,   53,   52,   53,  114,   55,
       63,   63,   54,   55,   87,   65,   54,   65,   65,   67,
       67,   80,   80,   87,  106,  106,  107,  115,  120,  140,
      140,  115,  193,  377,  204,  193,  376,  204,  371,  107,
      120,  204,  205,  369,  366,  205,  365,  362,  361,  205,
      380,  380,  359,  358,  356,  354,  350,  348,  345,  343,

      341,  340,  336,  335,  333,  332,  330,  329,  328,  327,
      326,  324,  323,  316,  315,  314,  313,  308,  303,  302,
      301,  298,  297,  296,  294,  292,  290,  289,  288,  287,
      285,  284,  282,  280,  279,  278,  275,  272,  271,  270,
      268,  267,  266,  265,  264,  263,  262,  260,  259,  257,
      254,  253,  252,  250,  249,  248,  246,  245,  243,  241,
      239,  236,  234,  231,  230,  228,  226,  225,  224,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  209,  207,  206,  203,  202,  201,  199,  198,  197,
      196,  195,  194,  192,  191,  190,  189,  188,  187,  186,

      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      173,  172,  171,  170,  167,  166,  165,  164,  161,  160,
      158,  157,  156,  154,  153,  151,  150,  148,  147,  146,
      144,  143,  142,  141,  139,  138,  137,  136,  135,  134,
      133,  132,  131,  130,  129,  127,  126,  125,  124,  123,
      122,  121,  119,  118,  117,  116,  112,  111,  110,  109,
      105,  104,  103,  102,  101,  100,   99,   98,   97,   96,
       95,   94,   92,   91,   90,   88,   86,   85,   84,   83,
       82,   81,   79,   78,   77,   76,   75,   74,   73,   72,
       71,   70,   69,   62,   56,   49,   47,   46,   45,   42,

       38,   37,   36,   34,   31,   30,   29,   28,   26,   23,
       15,    7,    5,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "polylex"
/*
 *
 *        P O L Y S   L E X I C A L   A N A L Y S E R
 *        P O L Y S   L E X I C A L   A N A L Y S E R
 *        P O L Y S   L E X I C A L   A N A L Y S E R
 *
 *       Written by Soren B. Engelsen (INRA 1993-94)
 *       Last revision: S.B.E. 1997
 */

#line 12 "polylex"
#include <stdio.h>
#include "polypars.tab.h"
extern   int lineno;
#line 704 "lex.yy.c"

#define INITIAL 0
#define XRAY 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 23 "polylex"

#line 894 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 380 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 414 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 24 "polylex"
ECHO;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "polylex"
{  ECHO; skipcommnts(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 27 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 29 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 31 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 32 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 33 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 34 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 35 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 36 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 37 "polylex"
{  ECHO; sscanf(yytext, "%d", &yylval.integer);
               return (INTEGER);
            }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 40 "polylex"
{  ECHO; sscanf(yytext, "%lf", &yylval.real);
               return (REAL);
            }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 43 "polylex"
{  ECHO; yylval.string = yytext;
               if (yylval.string[strlen(yylval.string)-1] != '"')
                  yyerror("Unterminated character string");
               return (QSTRING);
            }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "polylex"
{  ECHO; return yytext[0]; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "polylex"
{  ECHO; yylval.cmd = ATTACH;
               return (ATTACH);
            }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "polylex"
{  ECHO; yylval.cmd = BUILD;
               return (BUILD);
            }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "polylex"
{  ECHO; yylval.cmd = CALC;
               return (CALC);
            }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 62 "polylex"
{  ECHO; yylval.cmd = COORD;
               return (COORD);
            }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "polylex"
{  ECHO; yylval.cmd = CREATE;
               return (CREATE);
            }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "polylex"
{  ECHO; yylval.cmd = DATE;
               return (DATE);
            }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "polylex"
{  ECHO; yylval.cmd = DOUBLEHELIX;
               return (DOUBLEHELIX);
            }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 74 "polylex"
{  ECHO; yylval.cmd = END;
               return (END);
            }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 77 "polylex"
{  ECHO; yylval.cmd = ENER;
               return (ENER);
            }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 80 "polylex"
{  ECHO; yylval.cmd = GENERATE;
               return (GENERATE);
            }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "polylex"
{  ECHO; yylval.cmd = HELIX;
               return (HELIX);
            }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "polylex"
{  ECHO; yylval.cmd = HELP;
               return (HELP);
            }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "polylex"
{  ECHO; yylval.cmd = INIT;
               return (INIT);
            }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 92 "polylex"
{  ECHO; yylval.cmd = LABEL;
               return (LABEL);
            }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 95 "polylex"
{  ECHO; yylval.cmd = MINI;
               return (MINI);
            }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 "polylex"
{  ECHO; yylval.cmd = MODIFY;
               return (MODIFY);
            }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 101 "polylex"
{  ECHO; yylval.cmd = PRIMARY;
               return (PRIMARY);
            }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 104 "polylex"
{  ECHO; yylval.cmd = READ;
               return (READ);
            }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 107 "polylex"
{  ECHO; yylval.cmd = RECORD;
               return (RECORD);
            }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 110 "polylex"
{  ECHO; yylval.cmd = SET;
               return (SET);
            }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 113 "polylex"
{  ECHO; yylval.cmd = STOP;
               BEGIN 0;
               return (STOP);
            }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 117 "polylex"
{  ECHO; yylval.cmd = TIME;
               return (TIME);
            }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 120 "polylex"
{  ECHO; yylval.cmd = WRITE;
               return (WRITE);
            }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 123 "polylex"
{  ECHO; yylval.cmd = ALL;
               return (ALL);
            }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 126 "polylex"
{  ECHO; yylval.cmd = ANGLE;
               return (ANGLE);
            }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 129 "polylex"
{  ECHO; yylval.cmd = BOND;
               return (BOND);
            }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 132 "polylex"
{  ECHO; yylval.cmd = CARTE;
               return (CARTE);
            }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 135 "polylex"
{  ECHO; yylval.cmd = CHARGES;
               return (CHARGES);
            }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 138 "polylex"
{  ECHO; yylval.cmd = COORD;
               return (COORD);
            }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 141 "polylex"
{  ECHO; yylval.cmd = COPY;
               return (COPY);
            }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 144 "polylex"
{  ECHO; yylval.cmd = DEBUG;
               return (DEBUG);
            }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 147 "polylex"
{  ECHO; yylval.cmd = DTAB;
               return (DTAB);
            }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 150 "polylex"
{  ECHO; yylval.cmd = DERIV;
               return (DERIV);
            }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 153 "polylex"
{  ECHO; yylval.cmd = DIHED;
               return (DIHED);
            }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 156 "polylex"
{  ECHO; yylval.cmd = DIST;
               return (DIST);
            }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 159 "polylex"
{  ECHO; yylval.cmd = ENETOL;
               return (ENETOL);
            }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 162 "polylex"
{  ECHO; yylval.cmd = FRAC;
               return (FRAC);
            }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 165 "polylex"
{  ECHO; yylval.cmd = GRDTOL;
               return (GRDTOL);
            }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 168 "polylex"
{  ECHO; yylval.cmd = ID;
               return (ID);
            }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 171 "polylex"
{  ECHO; yylval.cmd = INTERNAL;
               return (INTERNAL);
            }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 174 "polylex"
{  ECHO; yylval.cmd = MASS;
               return (MASS);
            }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 177 "polylex"
{  ECHO; yylval.cmd = MAXIT;
               return (MAXIT);
            }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 180 "polylex"
{  ECHO; yylval.cmd = MAXFUN;
               return (MAXFUN);
            }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 183 "polylex"
{  ECHO; yylval.cmd = NBOND;
               return (NBOND);
            }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 186 "polylex"
{  ECHO; yylval.cmd = NFOLD;
               return (NFOLD);
            }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 189 "polylex"
{  ECHO; yylval.cmd = NOISE;
               return (NOISE);
            }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 192 "polylex"
{  ECHO; yylval.cmd = NREPS;
               return (NREPS);
            }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 195 "polylex"
{  ECHO; yylval.cmd = NSETS;
               return (NSETS);
            }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 198 "polylex"
{  ECHO; yylval.cmd = NSTR;
               return (NSTR);
            }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 201 "polylex"
{  ECHO; yylval.cmd = ONE;
               return (ONE);
            }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 204 "polylex"
{  ECHO; yylval.cmd = ORIENT;
               return (ORIENT);
            }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 207 "polylex"
{  ECHO; yylval.cmd = OPTIMIZE;
               return (OPTIMIZE);
            }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 210 "polylex"
{  ECHO; yylval.cmd = PARAM;
               return (PARAM);
            }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 213 "polylex"
{  ECHO; yylval.cmd = PHI;
               return (PHI);
            }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 216 "polylex"
{  ECHO; yylval.cmd = PHIB;
               return (PHIB);
            }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 219 "polylex"
{  ECHO; yylval.cmd = PHIE;
               return (PHIE);
            }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 222 "polylex"
{  ECHO; yylval.cmd = PHIINC;
               return (PHIINC);
            }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 225 "polylex"
{  ECHO; yylval.cmd = PSI;
               return (PSI);
            }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 228 "polylex"
{  ECHO; yylval.cmd = PSIB;
               return (PSIB);
            }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 231 "polylex"
{  ECHO; yylval.cmd = PSIE;
               return (PSIE);
            }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 234 "polylex"
{  ECHO; yylval.cmd = PSIINC;
               return (PSIINC);
            }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 237 "polylex"
{  ECHO; yylval.cmd = RANSEED;
               return (RANSEED);
            }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 240 "polylex"
{  ECHO; yylval.cmd = REF;
               return (REF);
            }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 243 "polylex"
{  ECHO; yylval.cmd = RECOPT;
               return (RECOPT);
            }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 246 "polylex"
{  ECHO; yylval.cmd = RGYR;
               return (RGYR);
            }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 249 "polylex"
{  ECHO; yylval.cmd = RMS;
               return (RMS);
            }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 252 "polylex"
{  ECHO; yylval.cmd = ROTBOND;
               return (ROTBOND);
            }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 255 "polylex"
{  ECHO; yylval.cmd = SAVE;
               return (SAVE);
            }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 258 "polylex"
{  ECHO; yylval.cmd = SHIFT;
               return (SHIFT);
            }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 261 "polylex"
{  ECHO; yylval.cmd = SILENT;
               return (SILENT);
            }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 264 "polylex"
{  ECHO; yylval.cmd = STAT;
               return (STAT);
            }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 267 "polylex"
{  ECHO; yylval.cmd = STAT;
               BEGIN XRAY;
               return (SYMMETRY);
            }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 271 "polylex"
{  ECHO; yylval.cmd = TITLE;
               return (TITLE);
            }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 274 "polylex"
{  ECHO; yylval.cmd = TORSION;
               return (TORSION);
            }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 277 "polylex"
{  ECHO; yylval.cmd = VOLUME;
               return (VOLUME);
            }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 280 "polylex"
{  ECHO; yylval.cmd = AMBER;
               return (AMBER);
            }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 283 "polylex"
{  ECHO; yylval.cmd = CHARMM;
               return (CHARMM);
            }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 286 "polylex"
{  ECHO; yylval.cmd = CFF;
               return (CFF);
            }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 289 "polylex"
{  ECHO; yylval.cmd = CSD;
               return (CSD);
            }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 292 "polylex"
{  ECHO; yylval.cmd = DAT;
               return (DAT);
            }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 295 "polylex"
{  ECHO; yylval.cmd = MM3;
               return (MM3);
            }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 298 "polylex"
{  ECHO; yylval.cmd = MONO;
               return (MONO);
            }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 301 "polylex"
{  ECHO; yylval.cmd = PDB;
               return (PDB);
            }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 304 "polylex"
{  ECHO; yylval.cmd = PF;
               return (PF);
            }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 307 "polylex"
{  ECHO; yylval.cmd = PLOT;
               return (PLOT);
            }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 310 "polylex"
{  ECHO; yylval.cmd = SYBYL;
               return (SYBYL);
            }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 313 "polylex"
{  ECHO; yylval.cmd = SPF;
               return (SPF);
            }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 316 "polylex"
{  ECHO; yylval.cmd = PIM;
               return (PIM);
            }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 319 "polylex"
{  ECHO; yylval.cmd = XYZ;
               return (XYZ);
            }
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 322 "polylex"
{  yylval.cmd = NL; 
               return(NL);
            }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 325 "polylex"
{  ECHO; yylval.string = yytext;
               return (NAME);
            }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 328 "polylex"
ECHO;
	YY_BREAK
#line 1736 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(XRAY):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 380 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 380 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 379);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 328 "polylex"


/*************************************************************************
   S O U R C E   S E C T I O N
*************************************************************************/
 skipcommnts()

{   int  ch, next;

    for (;;)
    {  ch = input();

       if (ch == '*')
          if ((next = input()) == '/')
          {  putchar(ch);
             putchar(next);
             return;
          }
          else
             unput(next);

       if (ch == '\n')
       {  lineno++;
          printf("\nPOLYS:%d > ", lineno);
       } 
       else
          putchar(ch);

    }
}  /* End of skipcommnts */


/* End of file */

